modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
issueTrackerURL="https://github.com/WoodenSlab/When_War_Arises/issues" #optional
license="${mod_license}" #mandatory

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/when-war-arises" #optional
author="${mod_author}" #optional
description='''${mod_description}''' #optional

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"